import {identity,db,bucket,json,failure,summary} from '@/lib/server';
import {runAgents} from '@/lib/agents';
import type {Requisition} from '@/lib/screening';
export async function POST(request:Request){try{const u=await identity(request);const now=new Date().toISOString();const lease=new Date(Date.now()+180000).toISOString();
 const task=await db().prepare("UPDATE tasks SET status='processing',attempts=attempts+1,lease_until=? WHERE id=(SELECT id FROM tasks WHERE owner=? AND (status='pending' OR (status='processing' AND lease_until<?)) AND attempts<3 ORDER BY created_at LIMIT 1) AND owner=? RETURNING *").bind(lease,u.userId,now,u.userId).first();
 if(!task){await db().prepare("UPDATE tasks SET status='failed',error='Retry limit reached. Use Retry failed to resume.' WHERE owner=? AND status='processing' AND lease_until<? AND attempts>=3").bind(u.userId,now).run();return json({done:true});}
 try{const source=await bucket().get(String(task.source_key));if(!source)throw new Error('Source document unavailable');const doc=await source.json<{text:string;name:string;filename:string}>();const row=await db().prepare('SELECT data FROM jobs WHERE id=? AND owner=?').bind(task.job_id,u.userId).first();if(!row)throw new Error('Requisition unavailable');const job=JSON.parse(String(row.data)) as Requisition;const assessment=await runAgents(doc.text,job);const reportKey=`${u.userId}/${task.job_id}/${task.id}/report.json`;await bucket().put(reportKey,JSON.stringify({text:doc.text,filename:doc.filename,assessment,jobSnapshot:job,screenedAt:new Date().toISOString()}));
 await db().batch([db().prepare('INSERT INTO candidates (id,owner,job_id,name,role,hash,summary,report_key,decision,review_note,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET summary=excluded.summary,report_key=excluded.report_key').bind(task.id,u.userId,task.job_id,doc.name,job.title,task.hash,JSON.stringify(summary(assessment)),reportKey,'Unreviewed','',new Date().toISOString()),db().prepare("UPDATE tasks SET status='complete',error=NULL,lease_until=NULL WHERE id=? AND owner=?").bind(task.id,u.userId),db().prepare('INSERT INTO audit (id,owner,action,detail,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),u.userId,'Screening completed',`${doc.name} · ${assessment.mode}`,new Date().toISOString())]);return json({id:task.id,done:false,status:'complete'});
 }catch(e){await db().prepare("UPDATE tasks SET status='failed',error=?,lease_until=NULL WHERE id=? AND owner=?").bind('Screening could not finish. Source is saved; retry this task.',task.id,u.userId).run();console.error('Screening failed',e instanceof Error?e.message:'unknown');return json({id:task.id,status:'failed',done:false});}
 }catch(e){return failure(e);}}
