import test from 'node:test';
import assert from 'node:assert/strict';
import {assess,fit,rankCandidates,compareCandidates,defaultJob,noGithub,yearsInHistory,sourceLines,requisitionWarnings,type Candidate} from '../lib/screening';
import {demoCandidates,demoSources} from '../lib/demo';
const now=new Date('2026-09-09');
const make=(text:string,id='a'):Candidate=>({id,name:id,jobId:'j',role:'Engineer',decision:'Unreviewed',reviewNote:'',createdAt:'2026-01-01',assessment:assess(text,defaultJob,noGithub,now)});
test('keyword stuffing is unsupported; absent skills are separately missing',()=>{const a=assess('Skills: Python, FastAPI, Kubernetes\nExperience\nWorked on support tickets.',defaultJob);assert.equal(a.dimensions[0].status,'unsupported');assert.equal(a.dimensions.find(x=>x.id==='cloud')?.status,'missing');assert.equal(a.dimensions.some(x=>x.status==='supported'),false);});
test('concrete work support cites exact original line without asserting external truth',()=>{const text='Skills: Python\nBuilt Python ingestion services processing 2000 records per hour.';const d=assess(text,defaultJob).dimensions[0];assert.equal(d.status,'supported');assert.deepEqual(d.evidence,[{line:2,quote:text.split('\n')[1]}]);assert.match(d.reason,/not independent verification/);});
test('K8s is equivalent while generic container orchestration remains partial',()=>{const a=assess('Deployed K8s workloads with readiness checks for ten production services.',defaultJob);assert.equal(a.dimensions.find(d=>d.id==='kubernetes')?.status,'supported');const b=assess('Implemented container orchestration for several production application services.',defaultJob);assert.equal(b.dimensions.find(d=>d.id==='kubernetes')?.status,'partial');});
test('word boundaries do not match unrelated substrings',()=>{assert.equal(assess('Built pythonsomething tools for the engineering workflow automation team.',defaultJob).dimensions[0].status,'missing');});
test('negated work statements never substantiate a skill',()=>{const d=assess('I have never deployed Kubernetes workloads in a production engineering team.',defaultJob).dimensions.find(x=>x.id==='kubernetes');assert.notEqual(d?.status,'supported');});
test('overlapping history is merged and education is not counted',()=>{assert.equal(yearsInHistory(sourceLines('Experience\nEngineer 2020–2024\nConsultant 2022–2025\nEducation\nB.Tech 2016–2020'),now),5);});
test('incomplete work history triggers unsupported claim, not accusation of contradiction',()=>{const a=assess('5 years of Python experience\nExperience\nIntern 2024–2025\nEducation\nB.Tech 2021–2025',defaultJob,noGithub,now);assert(a.flags.some(f=>f.title.includes('timeline')&&f.type==='unsupported'));assert(!a.flags.some(f=>f.type==='contradiction'));});
test('IC title alone does not contradict leadership; explicit denial does',()=>{const base='Experience\nIndividual Contributor 2021–2026\nLed a team of engineers to deliver the payments platform.';assert(!assess(base,defaultJob).flags.some(f=>f.type==='contradiction'));const a=assess(base+'\nI have never led a team.',defaultJob);const flag=a.flags.find(f=>f.type==='contradiction');assert(flag);assert.equal(flag.citations.length,2);});
test('network-unverified Github does not recommend rejection as missing code',()=>{const c=make('Skills: Python');c.assessment.github={...noGithub,status:'unverified'};assert.notEqual(fit(c,{...defaultJob,requireGithub:true}).recommendation,'Recommend reject');c.assessment.github={...noGithub};assert.equal(fit(c,{...defaultJob,requireGithub:true}).recommendation,'Recommend reject');assert.equal(c.decision,'Unreviewed');});
test('open-source priority is explicit and does not hide gaps',()=>{const a=make('Skills: Python','a'),b=make('Built Python services processing 200 requests per second.','b');a.assessment.github={...noGithub,status:'verified',externalMergedPRs:2};assert.equal(rankCandidates([b,a],defaultJob)[0].id,'a');assert(fit(a,defaultJob).tradeoffs.length>0);assert.equal(rankCandidates([a,b],{...defaultJob,prioritizeOSS:false})[0].id,'b');});
test('what-if actually recomputes readiness and preserves saved requisition',()=>{const c=make('Experience\nEngineer 2020–2026\nBuilt Python ingestion jobs processing 1000 records per hour.');const scenario={...defaultJob,minYears:0,salaryMax:0,criteria:defaultJob.criteria.map(c=>({...c,required:c.id==='python'}))};assert(!fit(c,defaultJob).complete);assert(fit(c,scenario).complete);assert.equal(defaultJob.criteria.filter(c=>c.required).length,4);});
test('head-to-head comparison returns criterion narratives, never an overall score',()=>{const a=make('Skills: Python','a'),b=make('Developed Python automation jobs for the monthly reporting system.','b');const r=compareCandidates(a,b,defaultJob);assert.equal(r.length,defaultJob.criteria.length);assert.match(r[0].narrative,/b provides stronger/);assert(!('score' in r[0]));});
test('junior plus five years surfaces a restrictive requisition',()=>{assert(requisitionWarnings({...defaultJob,level:'Junior',minYears:5}).some(x=>/restrictive/.test(x)));});
test('all demo citations are real source lines and no candidate fully matches',()=>{assert.equal(demoCandidates.length,12);for(const c of demoCandidates){const lines=demoSources[c.id].split('\n');for(const d of c.assessment.dimensions)for(const citation of [...d.claims,...d.evidence])assert.equal(citation.quote,lines[citation.line-1].trim());}assert(!demoCandidates.some(c=>fit(c,defaultJob).complete));});
test('1000 applications retain per-criterion dimensions and deterministic review order',()=>{const pool=Array.from({length:1000},(_,i)=>make(`Applicant ${i}\nExperience\nEngineer 2022–2026\nDeveloped Python ingestion jobs for warehouse reporting across regions.`,String(i)));const ranked=rankCandidates(pool,defaultJob);assert.equal(ranked.length,1000);assert.equal(new Set(ranked.map(c=>c.id)).size,1000);assert(ranked.every(c=>c.assessment.dimensions.length===6));});


import {reviewPlan,interviewBrief} from '../lib/review-plan';
test('role-agnostic review plan does not shortlist unsupported keyword claims',()=>{
 const job={...defaultJob,title:'Operations Specialist',minYears:0,salaryMax:0,criteria:[{id:'inventory',name:'Inventory management',required:true,aliases:['stock control']}]};
 const c=make('Skills: stock control');c.assessment=assess('Skills: stock control',job);
 const plan=reviewPlan(c,job);assert.equal(plan.title,'Request evidence before shortlisting');assert.equal(plan.items[0].status,'unsupported');assert.match(plan.items[0].question,/own contribution/);assert.equal(plan.items[0].citations[0].line,1);assert.match(interviewBrief(c,job),/Operations Specialist/);assert.equal(c.decision,'Unreviewed');
});
test('supported evidence and explicit conflicts lead to clarification, not automatic acceptance',()=>{
 const c=make('Built Python reporting services for the monthly inventory tracking workflow.');
 const job={...defaultJob,minYears:0,salaryMax:0,criteria:[defaultJob.criteria[0]]};
 c.assessment.flags.push({type:'contradiction',title:'Ownership conflict',reason:'Conflicting statements',citations:[{line:1,quote:'I built it'},{line:2,quote:'I did not build it'}]});
 const plan=reviewPlan(c,job);assert.match(plan.title,/Clarify/);assert.equal(plan.clarifications[0].citations.length,2);assert.match(plan.items[0].question,/trade-off/);assert.equal(c.decision,'Unreviewed');
});
