import {assess,defaultJob,noGithub,type Candidate} from './screening';
const examples=[
 ['Aarav Mehta','Platform Engineer','Experience\nPlatform Engineer | 2020–2026\nBuilt Python services processing 20000 requests per hour for payments.\nDeveloped FastAPI endpoints with pagination for the billing platform.\nDeployed K8s workloads across 12 services and reduced release time 40%.\nImplemented pytest integration tests for critical payment workflows.\nDesigned Kafka message queues for distributed systems with retry processing.\nExpected salary: 16 LPA'],
 ['Maya Chen','Backend Engineer','Experience\nBackend Engineer | 2021–2026\nDeveloped Python applications for retail inventory processing across stores.\nBuilt REST API endpoints serving 5000 users every day.\nDeployed AWS services using infrastructure templates for production applications.\nImplemented unit tests for 40 endpoints in the ordering service.\nSkills: Kubernetes, distributed systems\nExpected salary: 17 LPA'],
 ['Rohan Das','Software Engineer','Experience\nSoftware Engineer | 2022–2026\nBuilt Python data pipelines that reduced reporting delays by 30%.\nDeveloped Django RESTful services with access control for internal reporting.\nMaintained Kubernetes deployments for the analytics engineering team.\nSkills: AWS, Kafka\nExpected salary: 14 LPA'],
 ['Sofia Patel','Cloud Engineer','Experience\nCloud Engineer | 2023–2026\nDeployed Azure cloud deployment templates supporting 15 production services.\nMaintained K8s clusters for customer-facing applications with resource limits.\nBuilt integration tests for production deployment smoke testing across services.\nSkills: Python, FastAPI\nExpected salary: 15 LPA'],
 ['Ishaan Rao','Backend Developer','Experience\nBackend Developer | 2024–2026\nDeveloped Python ingestion jobs for financial records and audit trails.\nImplemented FastAPI services with rate limiting for 3000 users.\nDeployed Kubernetes applications with readiness checks for internal tools.\nExpected salary: 10 LPA'],
 ['Elena Cruz','Software Engineer','Experience\nSoftware Engineer | 2021–2026\nDeveloped Python microservices for warehouse operations across 20 facilities.\nBuilt REST API integration workflows for the shipment processing system.\nImplemented pytest tests and reduced release regressions by 25%.\nSkills: container orchestration\nExpected salary: 19 LPA'],
 ['Neel Shah','Full Stack Developer','Experience\nFull Stack Developer | 2023–2026\nBuilt Django applications for a customer support ticketing system.\nSkills: Python, Kubernetes, distributed systems\nExpected salary: 12 LPA'],
 ['Priya Nair','Software Engineer','Summary\n5 years of Python experience\nExperience\nSoftware Engineering Intern | 2024–2025\nBuilt Python scripts to automate 12 repetitive reporting workflows.\nEducation\nB.Tech | 2021–2025\nSkills: K8s, FastAPI, distributed systems\nExpected salary: 8 LPA'],
 ['Omar Hassan','API Developer','Experience\nAPI Developer | 2022–2026\nDeveloped FastAPI services with validation for a healthcare scheduling tool.\nImplemented Python ingestion jobs for appointment records and audit events.\nSkills: Kubernetes\nExpected salary: 14 LPA'],
 ['Ananya Sen','Engineering Associate','Summary\nExpert in Python, Kubernetes, FastAPI, AWS, distributed systems, pytest.\nExperience\nEngineering Associate | 2024–2026\nAttended software training and worked on support tickets.\nExpected salary: 11 LPA'],
 ['Leo Martin','Software Engineer','Experience\nSoftware Engineer | 2022–2026\nBuilt Python applications with queue processing for logistics workflows.\nLed a team of engineers to deliver the scheduling platform.\nCover note\nI have never led a team and have no management experience.\nSkills: FastAPI, Kubernetes\nExpected salary: 16 LPA'],
 ['Kavya Iyer','Data Engineer','Experience\nData Engineer | 2023–2026\nBuilt Python data validation services processing 2000 records per minute.\nDesigned Kafka pipelines for distributed systems with idempotent consumers.\nSkills: API development, Kubernetes\nExpected salary: 14 LPA']
];
export const demoSources=Object.fromEntries(examples.map((e,i)=>[`demo-${i+1}`,`${e[0]}\n${e[1]}\n${e[2]}`]));
export const demoCandidates:Candidate[]=examples.map((e,i)=>{const g={...noGithub};if(i===0||i===2){Object.assign(g,{status:'verified',repositories:i===0?8:5,externalMergedPRs:i===0?7:3,note:'Synthetic demo fixture: simulated public code and merged open-source contributions. No real GitHub account was checked.',links:[]});}return {id:`demo-${i+1}`,name:e[0],role:e[1],jobId:'demo',decision:'Unreviewed',reviewNote:'',createdAt:`2026-09-0${i%8+1}T10:00:00Z`,assessment:assess(demoSources[`demo-${i+1}`],defaultJob,g,new Date('2026-09-09')),synthetic:true};});
