export type Criterion = { id: string; name: string; required: boolean; aliases: string[] };
export type Requisition = { title: string; department: string; level: string; minYears: number; salaryMax: number; requireGithub: boolean; prioritizeOSS: boolean; criteria: Criterion[] };
export type Citation = { line: number; quote: string };
export type Dimension = { id: string; name: string; required: boolean; status: 'supported'|'partial'|'unsupported'|'missing'; confidence: 'high'|'medium'|'low'; claims: Citation[]; evidence: Citation[]; reason: string };
export type Flag = { type: 'unsupported'|'contradiction'|'missing'; title: string; reason: string; citations: Citation[] };
export type GithubEvidence = { status: 'not_provided'|'unverified'|'verified'|'invalid'; username?: string; url?: string; repositories: number; externalMergedPRs: number; checkedAt?: string; links: string[]; note: string };
export type Assessment = { dimensions: Dimension[]; flags: Flag[]; github: GithubEvidence; observedYears: number; salary: number|null; trace: {agent: string; outcome: string}[]; mode: 'rules'|'ai-assisted'; followups: string[]; version: string };
export type Candidate = { id: string; name: string; role: string; jobId: string; decision: string; reviewNote: string; createdAt: string; assessment: Assessment; synthetic?: boolean };
export const defaultJob: Requisition = { title:'Backend Engineer', department:'Engineering', level:'Mid-level', minYears:3, salaryMax:18, requireGithub:false, prioritizeOSS:true, criteria:[{id:'python',name:'Python',required:true,aliases:['python']},{id:'api',name:'API development',required:true,aliases:['rest api','restful','fastapi','django','api development']},{id:'kubernetes',name:'Kubernetes',required:true,aliases:['kubernetes','k8s']},{id:'cloud',name:'Cloud deployment',required:true,aliases:['aws','gcp','azure','cloud deployment','amazon web services']},{id:'distributed',name:'Distributed systems',required:false,aliases:['distributed systems','distributed system','event-driven','message queue','kafka']},{id:'testing',name:'Automated testing',required:false,aliases:['pytest','unit tests','integration tests','automated testing','test automation']}] };
export const noGithub: GithubEvidence = {status:'not_provided',repositories:0,externalMergedPRs:0,links:[],note:'No public GitHub profile provided. Private work or another portfolio can be reviewed by HR.'};
const ACTION = /\b(built|developed|implemented|deployed|maintained|designed|migrated|optimized|reduced|shipped|created|tested|contributed|integrated|operated|scaled|automated|delivered|led|managed)\b/i;
const NEGATION = /\b(no|never|without|not|lack|lacks|lacking)\b.{0,25}\b(experience|built|developed|deployed|worked|knowledge|used|led|managed)\b|\b(have not|haven't|did not|didn't|not yet|never used|no experience)\b/i;
export function sourceLines(text: string): Citation[] {return text.split(/\r?\n/).map((quote,i)=>({line:i+1,quote:quote.trim()})).filter(x=>x.quote);}
function match(line:string,term:string){const esc=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); return new RegExp('(?:^|[^a-z0-9])'+esc+'(?:$|[^a-z0-9])','i').test(line);}
export function yearsInHistory(lines:Citation[], now=new Date()): number {
 const intervals:[number,number][]=[]; let education=false;
 for(const l of lines){if(/^(education|qualifications|academic)\b/i.test(l.quote)){education=true;continue;}if(/^(experience|work|employment|projects|professional)\b/i.test(l.quote))education=false;
 if(education || /\b(b\.?tech|bachelor|university|college|master|degree)\b/i.test(l.quote))continue;
 const r=/(20\d{2})(?:[-/]\d{1,2})?\s*[–—-]\s*(20\d{2}|present|current)/i.exec(l.quote); if(!r)continue;
 const a=+r[1],b=/present|current/i.test(r[2])?now.getUTCFullYear()+now.getUTCMonth()/12:+r[2];if(a<=b && b<=now.getUTCFullYear()+1)intervals.push([a,b]);
 } intervals.sort((a,b)=>a[0]-b[0]); const merged:[number,number][]=[]; for(const [a,b]of intervals){const last=merged.at(-1);if(last&&a<=last[1])last[1]=Math.max(last[1],b);else merged.push([a,b]);}return Math.round(merged.reduce((n,[a,b])=>n+b-a,0)*10)/10;
}
export function assess(text:string,job:Requisition,github:GithubEvidence=noGithub,now=new Date()):Assessment {
 const lines=sourceLines(text); const flags:Flag[]=[];
 const dimensions:Dimension[]=job.criteria.map(c=>{const claims=lines.filter(l=>[c.name,...c.aliases].some(a=>match(l.quote,a))).slice(0,12);
 const evidence=claims.filter(l=>ACTION.test(l.quote)&&!NEGATION.test(l.quote)&&l.quote.split(/\s+/).length>=8&& !/^(skills|expertise|proficiencies)\s*:/i.test(l.quote));
 const outcome=evidence.some(l=>/\b\d+(?:\.\d+)?\s*(%|users|requests|tests|services|ms|seconds|hours|teams|endpoints)\b|\d+%/i.test(l.quote));
 const related=c.id==='kubernetes'&&lines.some(l=>/container orchestration/i.test(l.quote));
 const status=evidence.length?'supported':claims.length?'unsupported':related?'partial':'missing';
 const reason=evidence.length?`Application describes ${c.name} in specific work${outcome?' with a quantified outcome':''}. This corroborates the claim within the application; it is not independent verification.`:claims.length?'Mentioned in the application, but no specific action and work context corroborate the claim.':related?'Container orchestration is related to Kubernetes, but does not establish Kubernetes-specific experience.':'The application does not address this criterion.';
 const d:Dimension={id:c.id,name:c.name,required:c.required,status,confidence:evidence.length?(outcome?'high':'medium'):'low',claims,evidence,reason};
 if(status!=='supported')flags.push({type:status==='missing'?'missing':'unsupported',title:c.name,reason,citations:claims}); return d;});
 const observedYears=yearsInHistory(lines,now);
 for(const l of lines){const m=/\b(\d+(?:\.\d+)?)\+?\s*years?\b.{0,35}\b(experience|python|engineering|development)\b/i.exec(l.quote);if(m&&+m[1]>observedYears+1){flags.push({type:'unsupported',title:'Experience claim exceeds documented timeline',reason:`Claims ${m[1]} years; dated non-education history spans approximately ${observedYears} years after merging overlaps. Undated work or earlier projects may explain the gap; request clarification.`,citations:[l,...lines.filter(x=>/20\d{2}\s*[–—-]/.test(x.quote)&&x.line!==l.line).slice(0,5)]});}}
 const leadership=lines.find(l=>/\b(led|managed)\b.{0,30}\bteam/i.test(l.quote)&&!NEGATION.test(l.quote));
 const denial=lines.find(l=>/\b(never (led|managed)|no (team leadership|management) experience|did not (lead|manage))\b/i.test(l.quote));
 if(leadership&&denial)flags.push({type:'contradiction',title:'Conflicting leadership statements',reason:'The application both claims and explicitly denies leadership. Job title alone is not evidence of contradiction.',citations:[leadership,denial]});
 for(const d of dimensions){const negative=d.claims.find(l=>NEGATION.test(l.quote));if(negative&&d.evidence.length)flags.push({type:'contradiction',title:`Conflicting ${d.name} statements`,reason:'A negative claim conflicts with a described work example. Review context and dates before deciding.',citations:[negative,d.evidence[0]]});}
 const salaryLine=lines.find(l=>/\b(expected|expectation|salary|compensation)\b/i.test(l.quote)&&/\d+(?:\.\d+)?\s*(lpa|lakhs?)/i.test(l.quote));
 const salary=salaryLine?Number(/(\d+(?:\.\d+)?)\s*(?:lpa|lakhs?)/i.exec(salaryLine.quote)![1]):null;
 return {dimensions,flags,github,observedYears,salary,version:'1.0',mode:'rules',trace:[{agent:'Document agent',outcome:`Parsed ${lines.length} source lines; source text retained for review.`},{agent:'Skill mapper',outcome:`Checked ${job.criteria.length} criteria with explicit aliases; broader concepts remain partial.`},{agent:'Evidence verifier',outcome:`${dimensions.filter(d=>d.status==='supported').length} criteria have same-document corroboration.`},{agent:'Consistency auditor',outcome:`${flags.filter(f=>f.type==='contradiction').length} contradictions; ${observedYears} documented years (approximate).`},{agent:'GitHub verifier',outcome:github.note},{agent:'Review planner',outcome:'Prepared a review recommendation and targeted evidence questions. HR records the final decision.'}],followups:flags.filter(f=>f.type!=='contradiction').slice(0,6).map(f=>`Please share a specific project, your contribution, and a work sample for: ${f.title}.`) };
}
export function fit(candidate:Candidate,job:Requisition){const a=candidate.assessment;const dimensions=job.criteria.map(c=>({...a.dimensions.find(d=>d.id===c.id)??{id:c.id,name:c.name,status:'missing' as const,confidence:'low' as const,claims:[],evidence:[],reason:'New criterion; rerun screening to assess.'},required:c.required}));const required=dimensions.filter(d=>d.required);const supported=required.filter(d=>d.status==='supported').length;
 const tradeoffs=required.filter(d=>d.status!=='supported').map(d=>`${d.name}: ${d.status}`);
 if(job.minYears>a.observedYears)tradeoffs.push(`Experience: ${a.observedYears} documented / ${job.minYears} years required`);
 if(job.salaryMax>0){if(a.salary===null)tradeoffs.push('Salary expectation not provided');else if(a.salary>job.salaryMax)tradeoffs.push(`Salary: ₹${a.salary} LPA / ₹${job.salaryMax} LPA budget`);}
 if(job.requireGithub&&a.github.status!=='verified')tradeoffs.push(`GitHub: ${a.github.status.replace('_',' ')}`);
 const contradictory=a.flags.some(f=>f.type==='contradiction');if(contradictory)tradeoffs.push('Contradictory statements require clarification');
 const recommendation=job.requireGithub&&['not_provided','invalid'].includes(a.github.status)?'Recommend reject':!tradeoffs.length?'Ready for review':supported>=Math.ceil(required.length*.6)?'Consider with gaps':'Evidence needed';
 return {dimensions,supported,total:required.length,tradeoffs,recommendation,complete:tradeoffs.length===0};}
export function rankCandidates(candidates:Candidate[],job:Requisition){return [...candidates].sort((a,b)=>{const x=fit(a,job),y=fit(b,job); const oss=(c:Candidate)=>c.assessment.github.status==='verified'&&c.assessment.github.externalMergedPRs>0?1:0;return (job.prioritizeOSS?oss(b)-oss(a):0)||Number(y.complete)-Number(x.complete)||y.supported-x.supported||x.tradeoffs.length-y.tradeoffs.length||a.createdAt.localeCompare(b.createdAt);});}
export function requisitionWarnings(job:Requisition){const warnings:string[]=[];if(/junior|entry/i.test(job.level)&&job.minYears>=5)warnings.push(`A ${job.level.toLowerCase()} role requiring ${job.minYears}+ years may be overly restrictive. Review seniority and experience together.`);if(job.criteria.filter(c=>c.required).length>7)warnings.push('More than seven mandatory skills may narrow the pool. Consider which are trainable.');if(job.requireGithub)warnings.push('A public GitHub requirement excludes confidential or private work. Review alternatives before confirming a rejection.');return warnings;}
export function compareCandidates(a:Candidate,b:Candidate,job:Requisition){return job.criteria.map(c=>{const x=fit(a,job).dimensions.find(d=>d.id===c.id)!;const y=fit(b,job).dimensions.find(d=>d.id===c.id)!;return {criterion:c.name,a:x.status,b:y.status,narrative:x.status===y.status?`Both applications are ${x.status} for ${c.name}; inspect their cited work to compare depth.`:`${a.name}: ${x.status}; ${b.name}: ${y.status}. ${x.status==='supported'?a.name:y.status==='supported'?b.name:'Neither candidate'} provides stronger documented support on this dimension.`};});}
