import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {z} from 'zod';
export function db(){if(!env.DB)throw new Error('Database unavailable. Please try again.');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new Error('Document storage unavailable. Please try again.');return env.BUCKET;}
export const jobSchema=z.object({title:z.string().trim().min(2).max(100),department:z.string().max(80),level:z.string().max(40),minYears:z.number().min(0).max(40),salaryMax:z.number().min(0).max(500),requireGithub:z.boolean(),prioritizeOSS:z.boolean(),criteria:z.array(z.object({id:z.string().regex(/^[a-z0-9_-]{1,50}$/),name:z.string().trim().min(1).max(80),required:z.boolean(),aliases:z.array(z.string().trim().min(1).max(80)).max(20)})).min(1).max(20)}).refine(j=>new Set(j.criteria.map(c=>c.id)).size===j.criteria.length,'Criterion IDs must be unique');
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export async function identity(request:Request){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'Please sign in to access your workspace.');if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new HttpError(403,'Request origin is not allowed.');}return user;}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export function failure(error:unknown){if(error instanceof HttpError)return json({error:error.message},error.status);if(error instanceof z.ZodError)return json({error:error.issues.map(i=>i.message).join('; ')},400);console.error('Workspace operation failed',error instanceof Error?error.message:'unknown');return json({error:'This operation could not be completed. Your saved data is retained; please retry.'},503);}
export async function body(request:Request){if(Number(request.headers.get('content-length')||0)>250000)throw new HttpError(413,'Request is too large.');const value=await request.text();if(value.length>250000)throw new HttpError(413,'Request is too large.');try{return JSON.parse(value);}catch{throw new HttpError(400,'Invalid JSON.');}}
export async function log(owner:string,action:string,detail:string){await db().prepare('INSERT INTO audit (id,owner,action,detail,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),owner,action,detail,new Date().toISOString()).run();}
export function candidateRow(row:Record<string,unknown>){return {id:row.id,name:row.name,role:row.role,jobId:row.job_id,decision:row.decision,reviewNote:row.review_note,createdAt:row.created_at,assessment:JSON.parse(String(row.summary))};}
export function summary(a:import('./screening').Assessment){return {...a,dimensions:a.dimensions.map(d=>({...d,claims:[],evidence:[],reason:''})),flags:a.flags.map(f=>({...f,citations:[],reason:''})),trace:[],followups:[]};}
