import {identity,db,json,failure,body,jobSchema,log,candidateRow,HttpError} from '@/lib/server';
import {defaultJob} from '@/lib/screening';
import {aiConfigured} from '@/lib/agents';
import {z} from 'zod';
export async function GET(request:Request){try{const u=await identity(request);const profile=await db().prepare('SELECT * FROM profiles WHERE id=?').bind(u.userId).first();const jobs=await db().prepare('SELECT * FROM jobs WHERE owner=? ORDER BY created_at').bind(u.userId).all();const rows=await db().prepare('SELECT * FROM candidates WHERE owner=? ORDER BY created_at DESC LIMIT 5000').bind(u.userId).all();const tasks=await db().prepare('SELECT id,job_id,name,status,attempts,error,created_at FROM tasks WHERE owner=? ORDER BY created_at DESC LIMIT 5000').bind(u.userId).all();const history=await db().prepare('SELECT action,detail,created_at FROM audit WHERE owner=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all();return json({profile:profile||{name:u.displayName,email:u.email,company:'My workspace'},jobs:jobs.results.map(r=>({id:r.id,...JSON.parse(String(r.data))})),candidates:rows.results.map(candidateRow),tasks:tasks.results,history:history.results,aiEnabled:aiConfigured()});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const u=await identity(request),b=await body(request);const now=new Date().toISOString();if(b.action==='initialize'){await db().prepare('INSERT INTO profiles (id,name,email,company,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(u.userId,u.displayName,u.email,'My workspace',now).run();const existing=await db().prepare('SELECT id FROM jobs WHERE owner=? LIMIT 1').bind(u.userId).first();if(!existing)await db().prepare('INSERT INTO jobs (id,owner,data,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),u.userId,JSON.stringify(defaultJob),now).run();return json({ok:true});}
 if(b.action==='profile'){const p=z.object({name:z.string().trim().min(1).max(100),company:z.string().trim().min(1).max(100)}).parse(b);await db().prepare('INSERT INTO profiles (id,name,email,company,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,company=excluded.company,updated_at=excluded.updated_at').bind(u.userId,p.name,u.email,p.company,now).run();await log(u.userId,'Profile updated',p.company);return json({ok:true});}
 if(b.action==='job'){const job=jobSchema.parse(b.job);const id=b.id?z.string().uuid().parse(b.id):crypto.randomUUID();if(b.id){const found=await db().prepare('SELECT id FROM jobs WHERE id=? AND owner=?').bind(id,u.userId).first();if(!found)throw new HttpError(404,'Requisition not found.');await db().prepare('UPDATE jobs SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(job),id,u.userId).run();}else await db().prepare('INSERT INTO jobs (id,owner,data,created_at) VALUES (?,?,?,?)').bind(id,u.userId,JSON.stringify(job),now).run();await log(u.userId,'Requisition saved',`${job.title}; ${job.criteria.filter(c=>c.required).length} required criteria; minimum ${job.minYears} years`);return json({id});}
 if(b.action==='rescreen'){const id=z.string().uuid().parse(b.jobId);const job=await db().prepare('SELECT id FROM jobs WHERE id=? AND owner=?').bind(id,u.userId).first();if(!job)throw new HttpError(404,'Requisition not found.');await db().prepare("UPDATE tasks SET status='pending',attempts=0,error=NULL,lease_until=NULL WHERE owner=? AND job_id=? AND status IN ('complete','failed')").bind(u.userId,id).run();await log(u.userId,'Re-screen requested',id);return json({ok:true});}
 if(b.action==='retry'){await db().prepare("UPDATE tasks SET status='pending',error=NULL,attempts=0,lease_until=NULL WHERE owner=? AND status='failed'").bind(u.userId).run();await log(u.userId,'Retry requested','Failed tasks returned to queue.');return json({ok:true});}
 throw new HttpError(400,'Unknown action.');}catch(e){return failure(e);}}
